TOP_K = 5

RRF_SCORE_THRESHOLD = 0.08
MAX_HISTORY = 10

TOP_CONTEXT_CHUNKS = 4
RERANKER_MODEL = "BAAI/bge-reranker-base"

EMBEDDING_MODEL = "all-MiniLM-L6-v2"

LLM_MODEL = "llama-3.3-70b-versatile"

TEMPERATURE = 0.3

MAX_TOKENS = 1024

ENABLE_RAG = True

ENABLE_CITATIONS = True

ENABLE_MEMORY = True

ENABLE_HYBRID_SEARCH = False

ENABLE_QUERY_REWRITE = False

ENABLE_RERANKING = False